import { FAQ } from "@/types/faq";

const faqData: FAQ[] = [
  {
    id: 1,
    quest: "How can I create an AI Website? ",
    ans: "Creating a professional website for your business has never been easier! Tell us your business type, name, and key keywords, and our AI Website Builder will generate a personalized website you can customize in minutes. Get started today and build your online presence in no time!",
  },
  {
    id: 2,
    quest: "Is this AI Website Builder Free?",
    ans: "The AI Website Builder offers a Freemium model. While you can create a website for free, more advanced features are available through subscription.",
  },
  {
    id: 3,
    quest: "Is the website generated by AI mobile-friendly?",
    ans: "Yes, all websites generated by our AI are fully responsive and mobile-friendly. This means your website will automatically adjust and look great on any device, whether it's a desktop, tablet, or smartphone.",
  },
];

export default faqData;
